# id: 1
server:
  address: "server:12345"
loop:
  lapse: "0m20s"
  period: "5s"
log:
  level: "info"
batch: 
  #525 bytes is the maximum posible single bet lenght
  # 8kb / 525 bytes ~= 15 bets per batch
  # maximum batch size is 127, protocol limitations
  size: 15
